import{TILE,palettes,tiles,entityTypes,clone,makeScene,project,entity,validate,History,line,fill,collisionAt}from'./model.js';
import{drawTile,drawEntity,drawScene}from'./render.js';
import{Runtime}from'./runtime.js';
import{initializeScene,validateExtended,biomeNames,gameTypes}from'./model.js';
import{mountWorkbench}from'./workbench.js';
import{ProjectStore}from'./storage.js';
import{buildGameHTML}from'./export.js';
import{openProjectFile as chooseProjectFile,saveProjectFile}from'./platform.js';
let workbench=null;
const projectStore=new ProjectStore();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SKIN_KEY='pixel-forge-skin';
function applySkin(skin){const value=skin==='playground'?'playground':'classic';document.documentElement.dataset.skin=value;const toggle=$('#themeToggle');if(toggle){toggle.textContent=value==='playground'?'✦ Classic skin':'✦ Pixel Playground';toggle.setAttribute('aria-pressed',String(value==='playground'));toggle.title=value==='playground'?'Switch to Pixel Forge Classic':'Switch to Pixel Playground';}try{localStorage.setItem(SKIN_KEY,value)}catch{} }
const LAYOUT_KEY='pixel-forge-layout',defaultLayout={left:208,right:244,assets:200,leftCollapsed:false,rightCollapsed:false,assetsCollapsed:false};
function readLayout(){try{return {...defaultLayout,...JSON.parse(localStorage.getItem(LAYOUT_KEY)||'{}')}}catch{return {...defaultLayout}}}
let layout=readLayout();
function saveLayout(){try{localStorage.setItem(LAYOUT_KEY,JSON.stringify(layout))}catch{}}
function applyLayout(){const studio=document.querySelector('.studio'),left=document.querySelector('.left-panel'),right=document.querySelector('.inspector'),assets=document.querySelector('.asset-panel');if(!studio||!left||!right||!assets)return;studio.style.setProperty('--left-panel-width',`${layout.left}px`);studio.style.setProperty('--right-panel-width',`${layout.right}px`);studio.style.setProperty('--asset-panel-height',`${layout.assets}px`);studio.classList.toggle('left-collapsed',layout.leftCollapsed);studio.classList.toggle('right-collapsed',layout.rightCollapsed);left.classList.toggle('collapsed',layout.leftCollapsed);right.classList.toggle('collapsed',layout.rightCollapsed);assets.classList.toggle('collapsed',layout.assetsCollapsed);for(const [id,expanded] of [['collapseLeft',!layout.leftCollapsed],['collapseRight',!layout.rightCollapsed],['collapse',!layout.assetsCollapsed]]){const b=document.getElementById(id);if(b){b.setAttribute('aria-expanded',String(expanded));b.textContent=id==='collapseLeft'?(expanded?'‹':'›'):id==='collapseRight'?(expanded?'›':'‹'):(expanded?'⌄':'⌃')}}}
function initLayout(){applyLayout();document.getElementById('collapseLeft').onclick=()=>{layout.leftCollapsed=!layout.leftCollapsed;saveLayout();applyLayout();fit()};document.getElementById('collapseRight').onclick=()=>{layout.rightCollapsed=!layout.rightCollapsed;saveLayout();applyLayout();fit()};document.getElementById('collapse').onclick=()=>{layout.assetsCollapsed=!layout.assetsCollapsed;saveLayout();applyLayout();fit()};document.getElementById('resetLayout').onclick=()=>{layout={...defaultLayout};saveLayout();applyLayout();fit();note('Panel layout reset.')};for(const grip of document.querySelectorAll('.resize-grip')){grip.addEventListener('pointerdown',event=>{if((grip.classList.contains('left-resize-grip')&&layout.leftCollapsed)||(grip.classList.contains('right-resize-grip')&&layout.rightCollapsed)||(grip.classList.contains('asset-resize-grip')&&layout.assetsCollapsed))return;event.preventDefault();grip.setPointerCapture?.(event.pointerId);grip.classList.add('dragging');const startX=event.clientX,startY=event.clientY,start={...layout};const move=e=>{if(grip.classList.contains('left-resize-grip'))layout.left=Math.max(150,Math.min(360,start.left+e.clientX-startX));else if(grip.classList.contains('right-resize-grip'))layout.right=Math.max(190,Math.min(380,start.right-(e.clientX-startX)));else layout.assets=Math.max(120,Math.min(360,start.assets-(e.clientY-startY)));applyLayout();fit()};const end=()=>{grip.classList.remove('dragging');window.removeEventListener('pointermove',move);saveLayout()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',end,{once:true})})}}
let p=project(true),history=new History(),tool='pencil',tab='tiles',mode='world',layerId='terrain',tileId=1,entityType='player',selected=null,grid=true,showCollision=false,showCamera=false,crt=false,zoom=1,pan={x:90,y:0},runtime=null,drag=null,hover=null,spriteFrame=0,color=12,onion=false,animate=false,logs=['Pixel Forge is ready.','Original sample: Moonfern crossing.'],saveTimer;
applySkin((()=>{try{return localStorage.getItem(SKIN_KEY)||'classic'}catch{return'classic'}})());
const keys=new Set(),canvas=$('#world'),ctx=canvas.getContext('2d'),mini=$('#minimap'),mctx=mini.getContext('2d');
const tools=[['select','↖','V','Select and move entities'],['pencil','✎','B','Paint tiles or pixels'],['eraser','⌫','E','Erase tiles or pixels'],['fill','▨','F','Fill connected area'],['rectangle','□','R','Draw a filled rectangle'],['line','╱','L','Draw a line'],['eyedropper','⌾','I','Pick tile or color'],['entity','♟','N','Place an entity'],['collision','▧','C','Toggle tile collision'],['camera','▣','K','Move camera bounds'],['pan','✥','H','Pan the canvas']];
const hints={pencil:'Pencil · click or drag to paint',eraser:'Eraser · click or drag to erase',fill:'Fill · click a connected region',rectangle:'Rectangle · drag from corner to corner',line:'Line · drag from start to end',select:'Select · click an entity, drag to move',eyedropper:'Eyedropper · click a tile or pixel',entity:'Entity · click to place the selected type',collision:'Collision · click to toggle a cell',camera:'Camera · drag to reposition viewport',pan:'Pan · drag the canvas'};
function scene(){return p.scenes[p.activeScene]}
function layer(){return scene().layers.find(l=>l.id===layerId)||scene().layers[1]}
function note(message,error=false){$('#notification').textContent=message;$('#notification').classList.toggle('toast-error',error);logs.push(`${new Date().toLocaleTimeString()}  ${message}`);if(logs.length>100)logs.shift();if(tab==='console')renderAssets();}
function checkpoint(){history.push(p)}
function changed(){workbench?.syncSprite();p.updatedAt=Date.now();$('#saveStatus').textContent='● Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{projectStore.save(p);$('#saveStatus').textContent='● Saved locally';}catch{note('Browser storage is full. Use Save to keep a project file.',true);$('#saveStatus').textContent='● Save file needed';}},250);updateHistory();renderMini();}
function updateHistory(){$('#undo').disabled=!history.past.length||!!runtime;$('#redo').disabled=!history.future.length||!!runtime}
function undo(){if(runtime)return;p=history.undo(p);selected=null;changed();refresh()}
function redo(){if(runtime)return;p=history.redo(p);selected=null;changed();refresh()}
function setTool(t){tool=t;$$('#tools button').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$('#toolStatus').textContent=hints[t]||({path:'Path · click to add waypoints',stamp:'Stamp · drag to capture, click to place',measure:'Measure · drag between points','garden-prop':'Garden prop · click to place'})[t];canvas.style.cursor=t==='pan'?'grab':t==='select'?'default':'crosshair';if(t==='collision'){showCollision=true;$('#collision').classList.add('active')}if(t==='camera'){showCamera=true;$('#camera').classList.add('active')}}
$('#tools').innerHTML=tools.map(([id,icon,key,label])=>`<button data-tool="${id}" title="${label} (${key})" aria-label="${label} (${key})">${icon}</button>`).join('');$$('#tools button').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
function fit(){if(mode==='sprite'){zoom=1;pan={x:0,y:0};return;}zoom=Math.min((canvas.width-125)/(scene().width*16),(canvas.height-70)/(scene().height*16));zoom=Math.max(.35,zoom);pan={x:(canvas.width-scene().width*16*zoom)/2+22,y:(canvas.height-scene().height*16*zoom)/2};$('#zoomLabel').textContent=Math.round(zoom*100)+'%';}
function renderScenes(){const s=scene();$('#projectName').textContent=p.name;$('#sceneName').textContent=s.name;$('#mapSize').textContent=`${s.width} × ${s.height} tiles`;$('#sampleLabel').hidden=!p.sample;$('#canvasCaption').replaceChildren(document.createTextNode(s.name.toUpperCase()));const caption=document.createElement('span');caption.textContent=(p.sample?'ORIGINAL SAMPLE • ':'YOUR SCENE • ')+(gameTypes[s.gameType]||'Platformer').toUpperCase();$('#canvasCaption').append(caption);$('#scenes').replaceChildren();p.scenes.forEach((sc,i)=>{const b=document.createElement('button');b.className='scene-row'+(i===p.activeScene?' active':'');b.textContent='▦ '+sc.name;b.onclick=()=>{if(runtime)stop();p.activeScene=i;selected=null;layerId='terrain';changed();refresh();fit()};$('#scenes').append(b)});$('#biome').value=s.biome;}
function renderLayers(){$('#layers').replaceChildren();[...scene().layers].reverse().forEach(l=>{const row=document.createElement('div');row.className='layer-row'+(l.id===layerId?' selected':'');const eye=document.createElement('button');eye.textContent=l.visible?'◉':'○';eye.title=(l.visible?'Hide ':'Show ')+l.name;eye.onclick=()=>{checkpoint();l.visible=!l.visible;changed();renderLayers()};const name=document.createElement('button');name.className='layer-name';name.textContent=l.name;name.title='Select layer · double-click to rename';name.onclick=()=>{layerId=l.id;selected=null;renderLayers();renderInspector()};name.ondblclick=()=>{const value=prompt('Layer name',l.name);if(value?.trim()){checkpoint();l.name=value.trim();changed();renderLayers()}};const lock=document.createElement('button');lock.textContent=l.locked?'▣':'◇';lock.title=(l.locked?'Unlock ':'Lock ')+l.name;lock.onclick=()=>{checkpoint();l.locked=!l.locked;changed();renderLayers()};row.append(eye,name,lock);$('#layers').append(row)})}
function thumb(type,id){const c=document.createElement('canvas');c.width=32;c.height=32;const x=c.getContext('2d');x.imageSmoothingEnabled=false;if(type==='tile'){x.scale(1.5,1.5);drawTile(x,id,3,3,palettes[scene().biome])}else{const e=entity(id,10,8);if(id==='door'){e.x=6;e.y=0;}drawEntity(x,e,palettes[scene().biome]);}return c}
function setTab(t){tab=t;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));renderAssets()}
function renderAssets(){if(workbench?.renderAssets(tab))return;const holder=$('#assets');holder.className=tab==='console'?'console':'asset-grid';holder.replaceChildren();$('.asset-filters').hidden=['animation','console'].includes(tab);if(tab==='console'){holder.textContent=logs.join('\n');return;}if(tab==='animation'){holder.className='sprite-controls';const text=document.createElement('span');text.textContent=`Sprite frames · ${p.sprite.frames.length}`;holder.append(text);for(let i=0;i<p.sprite.frames.length;i++){const b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0');b.classList.toggle('active',spriteFrame===i);b.onclick=()=>{spriteFrame=i;setMode('sprite');renderAssets()};holder.append(b)}const duplicate=document.createElement('button');duplicate.textContent='+ Duplicate frame';duplicate.onclick=()=>{checkpoint();p.sprite.frames.push([...p.sprite.frames[spriteFrame]]);spriteFrame=p.sprite.frames.length-1;changed();renderAssets()};const play=document.createElement('button');play.textContent=animate?'■ Pause preview':'▶ Animate';play.onclick=()=>{animate=!animate;animationStart=performance.now()/1000;setMode('sprite');renderAssets()};const label=document.createElement('label');label.textContent=' Frame ms ';const timing=document.createElement('input');timing.type='number';timing.min=30;timing.max=2000;timing.value=p.sprite.timing;timing.onchange=()=>{checkpoint();p.sprite.timing=Math.max(30,Math.min(2000,+timing.value||160));changed()};label.append(timing);holder.append(duplicate,play,label);return;}
if(tab==='sprites'){holder.className='sprite-controls';const b=document.createElement('button');b.textContent='✎ Edit custom sprite';b.onclick=()=>setMode('sprite');const imp=document.createElement('button');imp.textContent='↑ Import PNG sheet';imp.onclick=()=>$('#spriteInput').click();const exp=document.createElement('button');exp.textContent='↓ Export PNG sheet';exp.onclick=exportSprite;const explanation=document.createElement('span');explanation.textContent='Original artwork · transparent frames';explanation.style.color='var(--muted)';holder.append(b,imp,exp,explanation);$('#assetCount').textContent='1 sprite';return;}
const list=tab==='entities'?entityTypes.filter(t=>t!=='prop').map((t,i)=>({id:t,name:t[0].toUpperCase()+t.slice(1)})):tiles;const filtered=list.filter(a=>a.name.toLowerCase().includes($('#assetSearch').value.toLowerCase())&&(!workbench?.assetFilter||workbench.assetFilter(a,tab)));$('#assetCount').textContent=filtered.length+' assets';filtered.forEach(a=>{const b=document.createElement('button');b.className='asset'+((tab==='tiles'?tileId===a.id:entityType===a.id)?' active':'');b.title=a.name+(a.category?' · '+a.category:' · click, then place on canvas');b.draggable=true;b.ondragstart=e=>e.dataTransfer.setData('application/pixel-forge',JSON.stringify({tab,id:a.id}));b.append(thumb(tab==='tiles'?'tile':'entity',a.id));const label=document.createElement('span');label.textContent=a.name;b.append(label);b.onclick=()=>{workbench?.touchAsset(tab,a.id);selected=null;if(tab==='tiles'){tileId=a.id;if(['entities','background'].includes(layerId))layerId=a.solid?'terrain':'details';setTool('pencil')}else{entityType=a.id;layerId='entities';setTool('entity')}renderAssets();renderLayers();renderInspector()};holder.append(b)});workbench?.renderGardenKit()}
function section(title){const d=document.createElement('div');d.className='inspect-section';const h=document.createElement('h3');h.textContent=title;d.append(h);$('#inspection').append(d);return d}
function field(parent,label,value,onChange,options){const l=document.createElement('label');l.className='field';const s=document.createElement('span');s.textContent=label;l.append(s);let input;if(options){input=document.createElement('select');options.forEach(v=>{const o=document.createElement('option');o.value=typeof v==='string'?v:v[0];o.textContent=typeof v==='string'?v:v[1];input.append(o)});input.value=value}else{input=document.createElement('input');input.type=typeof value==='boolean'?'checkbox':typeof value==='number'?'number':'text';if(input.type==='checkbox')input.checked=value;else input.value=value;}input.onchange=()=>{if(runtime){renderInspector();return;}checkpoint();onChange(input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value);changed();renderScenes();renderInspector()};l.append(input);parent.append(l);return input}
function renderInspector(){if(workbench?.renderInspector())return;const box=$('#inspection');box.replaceChildren();if(mode==='sprite'){const sec=section('PIXEL WORKSHOP');field(sec,'Canvas size',p.sprite.size,v=>{if(!confirm('Resize the sprite? Existing pixels are cropped or padded.'))return;const size=+v,old=p.sprite.size;p.sprite.frames=p.sprite.frames.map(f=>{const n=Array(size*size).fill(null);for(let y=0;y<Math.min(size,old);y++)for(let x=0;x<Math.min(size,old);x++)n[y*size+x]=f[y*old+x];return n});p.sprite.size=size;},[8,16,24,32,64].map(n=>[n,`${n} × ${n}`]));field(sec,'Onion skin',onion,v=>onion=v);field(sec,'Playback',p.sprite.mode,v=>p.sprite.mode=v,['loop','ping-pong','one-shot']);const flip=document.createElement('button');flip.textContent='↔ Flip frame';flip.onclick=()=>{checkpoint();const n=p.sprite.size,f=p.sprite.frames[spriteFrame];for(let y=0;y<n;y++)for(let x=0;x<n/2;x++){let a=y*n+x,b=y*n+n-1-x;[f[a],f[b]]=[f[b],f[a]];}changed()};sec.append(flip);const n=document.createElement('p');n.className='inspector-note';n.textContent='Choose a swatch below. Pencil, eraser, fill, rectangle, line and eyedropper work directly on pixels. Export a transparent PNG sheet from Sprites.';box.append(n);return;}
const e=scene().entities.find(x=>x.id===selected),t=tiles.find(x=>x.id===tileId);const title=document.createElement('div');title.className='inspect-title';title.append(thumb(e?'entity':'tile',e?e.type:t.id));const titleText=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=e?e.name:t.name+' tile';small.textContent=e?'ENTITY / '+e.type.toUpperCase():'TILE / '+t.category.toUpperCase();titleText.append(strong,small);title.append(titleText);box.append(title);
if(e){let sec=section('TRANSFORM');field(sec,'Name',e.name,v=>e.name=v);field(sec,'Position X',e.x,v=>e.x=Math.max(0,Math.min(scene().width*16-e.w,v)));field(sec,'Position Y',e.y,v=>e.y=Math.max(0,Math.min(scene().height*16-e.h,v)));field(sec,'Visible',e.visible,v=>e.visible=v);if(e.type==='player'||e.type==='enemy'){sec=section('BEHAVIOR');field(sec,'Speed',e.speed,v=>e.speed=Math.max(0,Math.min(500,v)));field(sec,'Health',e.health,v=>e.health=Math.max(1,Math.min(20,v)));if(e.type==='player'){field(sec,'Jump velocity',e.jump,v=>e.jump=Math.max(50,Math.min(800,v)));field(sec,'Gravity',e.gravity,v=>e.gravity=Math.max(100,Math.min(2400,v)))}else{field(sec,'Behavior',e.behavior,v=>e.behavior=v,['patrol','stationary']);field(sec,'Patrol range',e.patrol,v=>e.patrol=Math.max(0,Math.min(500,v)))}}const sec2=section('ENTITY ACTIONS');const duplicate=document.createElement('button');duplicate.textContent='＋ Duplicate';duplicate.onclick=duplicateEntity;const del=document.createElement('button');del.textContent='× Delete';del.onclick=deleteEntity;sec2.append(duplicate,del);
}else{let sec=section('TILE PROPERTIES');const values=[['Tile size','16 × 16 px'],['Category',t.category],['Collision',t.id===4?'One-way':t.solid?'Solid':t.id===5?'Damage':'None'],['Active layer',layer().name]];for(const[a,b]of values){const row=document.createElement('div');row.className='field';const label=document.createElement('span'),value=document.createElement('span');label.textContent=a;value.textContent=b;value.className='value';row.append(label,value);sec.append(row)}sec=section('SCENE SETTINGS');field(sec,'Name',scene().name,v=>scene().name=v);field(sec,'Camera width',scene().camera.w,v=>scene().camera.w=Math.max(160,Math.min(640,v)));field(sec,'Camera height',scene().camera.h,v=>scene().camera.h=Math.max(120,Math.min(384,v)));const musicOptions=[['','No automatic music'],...(p.audio?.music||[]).map(a=>[a.id,a.name])];field(sec,'Scene music',scene().musicId||'',v=>scene().musicId=v,musicOptions);const info=document.createElement('div');info.className='inspector-note';info.textContent='Select an entity on the canvas to edit movement, health and position. Scene music starts automatically when playtest/export begins or when entering this scene.';box.append(info);}}
function renderPalette(){$('#swatches').replaceChildren();palettes[scene().biome].forEach((c,i)=>{const b=document.createElement('button');b.className='swatch'+(i===color?' active':'');b.style.background=c;b.title=`Color ${i+1}: ${c}`;b.setAttribute('aria-label',b.title);b.onclick=()=>{color=i;renderPalette()};$('#swatches').append(b)});$('#paletteName').textContent=biomeNames[scene().biome]||scene().biome}
function renderMini(){drawScene(mctx,scene(),{scale:192/(scene().width*16),width:192,height:96,assets:p.assets,customSprite:p.sprite});mctx.strokeStyle='#ec6e88';mctx.lineWidth=1;const factor=192/(scene().width*16);mctx.strokeRect(-pan.x/zoom*factor,-pan.y/zoom*factor,canvas.width/zoom*factor,canvas.height/zoom*factor)}
function refresh(){workbench?.restorePalette();spriteFrame=Math.max(0,Math.min(spriteFrame,p.sprite.frames.length-1));renderScenes();renderLayers();renderAssets();renderInspector();renderPalette();updateHistory();renderMini();setTool(tool);workbench?.refresh()}
function resize(){const r=canvas.getBoundingClientRect();canvas.width=Math.round(r.width);canvas.height=Math.round(r.height);ctx.imageSmoothingEnabled=false;renderMini()}
new ResizeObserver(resize).observe($('#canvasArea'));
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function spriteGeometry(){const size=Math.floor(Math.min(canvas.width-140,canvas.height-65)/p.sprite.size);return{scale:Math.max(2,size),x:Math.floor((canvas.width-p.sprite.size*size)/2)+20,y:Math.floor((canvas.height-p.sprite.size*size)/2)-5}}
function cell(e){const q=point(e),v=mode==='sprite'?spriteGeometry():{...pan,scale:zoom};return{x:Math.floor((q.x-v.x)/v.scale/(mode==='sprite'?1:16)),y:Math.floor((q.y-v.y)/v.scale/(mode==='sprite'?1:16))}}
function inBounds(a){return a.x>=0&&a.y>=0&&a.x<(mode==='sprite'?p.sprite.size:scene().width)&&a.y<(mode==='sprite'?p.sprite.size:scene().height)}
function canEdit(){if(mode==='sprite')return true;if(layer().locked||!layer().visible){note('This layer is locked or hidden. Unlock or show it to edit.',true);return false}return true}
function writeCell(x,y,erase=false){if(!inBounds({x,y}))return;if(mode==='sprite')p.sprite.frames[spriteFrame][y*p.sprite.size+x]=erase?null:palettes[scene().biome][color];else{const map=layer().tiles;if(erase){delete map[`${x},${y}`];delete scene().tileTransforms?.[`${x},${y}`];}else{map[`${x},${y}`]=tileId;if(workbench?.tileTransform)scene().tileTransforms[`${x},${y}`]={...workbench.tileTransform};}}}
function drawStroke(a,b,erase=false){for(const[x,y]of line(a.x,a.y,b.x,b.y))writeCell(x,y,erase)}
function place(a){if(!inBounds(a)||scene().layers.find(l=>l.id==='entities')?.locked){note('Unlock the Entities layer to place objects.',true);return;}if(entityType==='player'){const existing=scene().entities.find(e=>e.type==='player');if(existing){existing.x=a.x*16;existing.y=a.y*16;selected=existing.id;return;}}const e=entity(entityType,a.x*16,a.y*16);scene().entities.push(e);selected=e.id;}
canvas.onpointerdown=e=>{if(runtime)return;canvas.focus();canvas.setPointerCapture(e.pointerId);const q=point(e),a=cell(e);if(workbench?.pointerDown(e,a,q))return;if(tool==='pan'||keys.has(' ')||e.button===1){drag={type:'pan',q,pan:{...pan}};return;}if(!inBounds(a))return;if(tool==='eyedropper'){if(mode==='sprite'){const c=p.sprite.frames[spriteFrame][a.y*p.sprite.size+a.x],i=palettes[scene().biome].indexOf(c);if(i>=0){color=i;renderPalette()}}else{tileId=layer().tiles[`${a.x},${a.y}`]||tileId;renderAssets();renderInspector()}return;}if(mode==='world'&&tool==='select'){const x=(q.x-pan.x)/zoom,y=(q.y-pan.y)/zoom;const en=[...scene().entities].reverse().find(en=>x>=en.x-2&&x<=en.x+en.w+2&&y>=en.y-2&&y<=en.y+en.h+2);selected=en?.id||null;if(en&&!scene().layers.find(l=>l.id==='entities')?.locked){checkpoint();drag={type:'entity',q,x:en.x,y:en.y,e:en};}renderInspector();return;}if(!canEdit())return;checkpoint();if(tool==='entity'&&mode==='world'){place(a);changed();renderInspector();return;}if(tool==='camera'&&mode==='world'){drag={type:'camera',q,x:scene().camera.x,y:scene().camera.y};return;}if(tool==='collision'&&mode==='world'){scene().collision[`${a.x},${a.y}`]=!collisionAt(scene(),a.x,a.y);changed();return;}if(tool==='fill'){if(mode==='sprite'){const n=p.sprite.size,map={};p.sprite.frames[spriteFrame].forEach((v,i)=>{if(v)map[`${i%n},${Math.floor(i/n)}`]=v});fill(map,a.x,a.y,palettes[scene().biome][color],n,n);p.sprite.frames[spriteFrame]=Array.from({length:n*n},(_,i)=>map[`${i%n},${Math.floor(i/n)}`]||null);}else fill(layer().tiles,a.x,a.y,tileId,scene().width,scene().height);changed();return;}drag={type:tool,a,b:a};if(tool==='pencil'||tool==='eraser'){writeCell(a.x,a.y,tool==='eraser');changed()}};
canvas.onpointermove=e=>{const a=cell(e);hover=a;workbench?.pointerMove(e,a,point(e));$('#coordinates').textContent=`X ${String(a.x).padStart(2,'0')}   Y ${String(a.y).padStart(2,'0')}`;if(!drag)return;const q=point(e);if(drag.type==='pan'){pan.x=drag.pan.x+q.x-drag.q.x;pan.y=drag.pan.y+q.y-drag.q.y;renderMini();return;}if(drag.type==='entity'){drag.e.x=Math.max(0,Math.min(scene().width*16-drag.e.w,Math.round((drag.x+(q.x-drag.q.x)/zoom)/8)*8));drag.e.y=Math.max(0,Math.min(scene().height*16-drag.e.h,Math.round((drag.y+(q.y-drag.q.y)/zoom)/8)*8));changed();return;}if(drag.type==='camera'){scene().camera.x=Math.max(0,Math.round(drag.x+(q.x-drag.q.x)/zoom));scene().camera.y=Math.max(0,Math.round(drag.y+(q.y-drag.q.y)/zoom));changed();return;}if(!inBounds(a))return;if(drag.type==='pencil'||drag.type==='eraser'){drawStroke(drag.b,a,drag.type==='eraser');changed();}drag.b=a;};
canvas.onpointerup=()=>{workbench?.pointerUp();if(!drag)return;if(drag.type==='rectangle'){for(let y=Math.min(drag.a.y,drag.b.y);y<=Math.max(drag.a.y,drag.b.y);y++)for(let x=Math.min(drag.a.x,drag.b.x);x<=Math.max(drag.a.x,drag.b.x);x++)writeCell(x,y);changed()}if(drag.type==='line'){drawStroke(drag.a,drag.b);changed()}drag=null;renderInspector()};canvas.onpointercancel=()=>{drag=null};canvas.onpointerleave=()=>hover=null;
canvas.onwheel=e=>{e.preventDefault();if(mode==='sprite'||runtime)return;zoomAt(zoom*(e.deltaY<0?1.12:1/1.12),point(e))};
function zoomAt(n,q={x:canvas.width/2,y:canvas.height/2}){n=Math.max(.3,Math.min(5,n));pan.x=q.x-(q.x-pan.x)*n/zoom;pan.y=q.y-(q.y-pan.y)*n/zoom;zoom=n;$('#zoomLabel').textContent=Math.round(zoom*100)+'%';renderMini()}
canvas.ondragover=e=>e.preventDefault();canvas.ondrop=e=>{e.preventDefault();if(runtime||mode!=='world')return;try{const data=JSON.parse(e.dataTransfer.getData('application/pixel-forge'));checkpoint();if(data.tab==='entities'){entityType=data.id;place(cell(e));}else{tileId=data.id;if(canEdit())writeCell(cell(e).x,cell(e).y);}changed();renderInspector()}catch{note('Drag an asset from this editor onto the canvas.',true)}};
function renderSprite(time){const g=spriteGeometry(),n=p.sprite.size;ctx.fillStyle='#14141b';ctx.fillRect(0,0,canvas.width,canvas.height);const f=p.sprite.frames;let index=spriteFrame;if(animate){let frame=Math.floor(time/(p.sprite.timing/1000));if(p.sprite.mode==='ping-pong'&&f.length>1){const cycle=(f.length-1)*2;frame%=cycle;index=frame<f.length?frame:cycle-frame;}else index=p.sprite.mode==='one-shot'?Math.min(f.length-1,frame):frame%f.length;}for(let y=0;y<n;y++)for(let x=0;x<n;x++){ctx.fillStyle=(x+y)%2?'#262631':'#202029';ctx.fillRect(g.x+x*g.scale,g.y+y*g.scale,g.scale,g.scale);if(onion&&index>0&&f[index-1][y*n+x]){ctx.globalAlpha=.25;ctx.fillStyle=f[index-1][y*n+x];ctx.fillRect(g.x+x*g.scale,g.y+y*g.scale,g.scale,g.scale);ctx.globalAlpha=1;}if(f[index][y*n+x]){ctx.fillStyle=f[index][y*n+x];ctx.fillRect(g.x+x*g.scale,g.y+y*g.scale,g.scale,g.scale);}}if(grid){ctx.strokeStyle='#ffffff16';ctx.lineWidth=1;for(let i=0;i<=n;i++){ctx.beginPath();ctx.moveTo(g.x+i*g.scale,g.y);ctx.lineTo(g.x+i*g.scale,g.y+n*g.scale);ctx.moveTo(g.x,g.y+i*g.scale);ctx.lineTo(g.x+n*g.scale,g.y+i*g.scale);ctx.stroke();}}}
let last=performance.now(),animationStart=last/1000;
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;ctx.imageSmoothingEnabled=false;if(runtime){runtime.update(dt,keys);runtime.render(ctx,canvas.width,canvas.height)}else if(mode==='sprite')renderSprite(now/1000-animationStart);else{drawScene(ctx,scene(),{...pan,scale:zoom,grid,collisions:showCollision,camera:showCamera,selected:scene().entities.find(e=>e.id===selected),time:scene().garden?.animate&&!p.settings.reducedMotion?now/1000:0,assets:p.assets,customSprite:p.sprite,paths:tool==='path'});if(hover&&inBounds(hover)&&!['pan','select'].includes(tool)){ctx.strokeStyle='#f4e6c3';ctx.lineWidth=1;ctx.strokeRect(Math.round(pan.x+hover.x*16*zoom),Math.round(pan.y+hover.y*16*zoom),16*zoom,16*zoom);}if(drag&&['rectangle','line'].includes(drag.type)){ctx.strokeStyle='#ec6e88';ctx.lineWidth=2;if(drag.type==='rectangle')ctx.strokeRect(pan.x+Math.min(drag.a.x,drag.b.x)*16*zoom,pan.y+Math.min(drag.a.y,drag.b.y)*16*zoom,(Math.abs(drag.a.x-drag.b.x)+1)*16*zoom,(Math.abs(drag.a.y-drag.b.y)+1)*16*zoom);else{ctx.beginPath();ctx.moveTo(pan.x+(drag.a.x+.5)*16*zoom,pan.y+(drag.a.y+.5)*16*zoom);ctx.lineTo(pan.x+(drag.b.x+.5)*16*zoom,pan.y+(drag.b.y+.5)*16*zoom);ctx.stroke();}}}if(crt){ctx.fillStyle='#00000028';for(let y=0;y<canvas.height;y+=3)ctx.fillRect(0,y,canvas.width,1)}workbench?.drawOverlay(ctx);requestAnimationFrame(frame)}
async function restartPlaytest(){if(!runtime)return;const muted=runtime.muted;try{runtime.dispose?.();runtime=new Runtime(scene(),p);await runtime.unlockAudio();runtime.setMuted(muted);$('#mutePlaytest').textContent=muted?'🔇 Unmute':'🔊 Mute';$('#mutePlaytest').setAttribute('aria-pressed',String(muted));}catch(e){note('Playtest restart failed: '+e.message,true)}}
async function play(){if(tab==='market')setTab('tiles');if(runtime){stop();return;}try{runtime=new Runtime(scene(),p);await runtime.unlockAudio();runtime.setMuted(false);keys.clear();$('#play').hidden=true;$('#stop').hidden=false;$('#playHint').hidden=false;$('#mutePlaytest').hidden=false;$('#mutePlaytest').textContent='🔊 Mute';$('#mutePlaytest').setAttribute('aria-pressed','false');$('#canvasCaption').hidden=true;$('#tools').hidden=true;$('#runtimeStatus').textContent='● PLAYTEST';updateHistory();note('Playtest started. Your editable scene is preserved.');canvas.focus()}catch(e){note(e.message,true)}}
function stop(){if(runtime)runtime.dispose?.();runtime=null;keys.clear();$('#play').hidden=false;$('#stop').hidden=true;$('#playHint').hidden=true;$('#mutePlaytest').hidden=true;$('#canvasCaption').hidden=false;$('#tools').hidden=false;$('#runtimeStatus').textContent='EDIT MODE';updateHistory();note('Back in the editor. Scene unchanged by playtest.')}
$('#mutePlaytest').onclick=()=>{if(!runtime)return;const muted=!runtime.muted;runtime.setMuted(muted);const b=$('#mutePlaytest');b.textContent=muted?'🔇 Unmute':'🔊 Mute';b.setAttribute('aria-pressed',String(muted));};
function setMode(m){if(runtime)stop();mode=m;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('#canvasCaption').hidden=m==='sprite';renderInspector();if(m==='sprite')setTool('pencil');else fit();}
async function download(data,name,type='application/json'){return saveProjectFile(data,name,type)}
const MAX_AUDIO_FILE=4*1024*1024,MAX_AUDIO_TOTAL=8*1024*1024;
function readDataURL(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Could not read the audio file.'));reader.readAsDataURL(file)})}
function importAudio(kind){const input=$('#audioInput');input.dataset.kind=kind;input.value='';input.click()}
function updateAudio(id,kind,patch){const asset=p.audio[kind].find(a=>a.id===id);if(!asset)return;checkpoint();Object.assign(asset,patch);changed();renderAssets()}
function removeAudio(id,kind){const asset=p.audio[kind].find(a=>a.id===id);if(!asset||!confirm(`Delete “${asset.name}”? Undo restores it.`))return;checkpoint();p.audio[kind]=p.audio[kind].filter(a=>a.id!==id);if(kind==='music')for(const s of p.scenes)if(s.musicId===id)s.musicId='';for(const s of p.scenes)for(const rule of s.events||[])if(rule.action==='sound'&&rule.value===id){rule.value='';rule.enabled=false;}changed();renderAssets()}
async function save(){try{if(await download(JSON.stringify(p,null,2),p.name.replace(/[^a-z0-9]/gi,'-').toLowerCase()+'.pixel.json')){changed();note('Project saved. Includes scenes, sprites, palettes and settings.')}}catch(error){note('Save failed: '+error.message,true)}}
function loadProject(next){p=validateExtended(next);history=new History();selected=null;spriteFrame=0;layerId='terrain';if(runtime)stop();mode='world';$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode==='world'));changed();refresh();fit();$('#welcome').close();}
function welcome(){const r=$('#recent');r.replaceChildren();try{const saved=JSON.parse(localStorage.getItem('pixel-forge-autosave'));if(saved){const b=document.createElement('button');b.textContent='↶ Resume: '+saved.name;b.style.marginBottom='16px';b.onclick=()=>{try{loadProject(saved);note('Restored your last local autosave.')}catch(e){note(e.message,true)}};r.append(b)}}catch{}$('#welcome').showModal()}
$('#newProject').onclick=()=>{if(!p.sample&&!confirm('Start a new empty project? Save your current project first if needed.'))return;const name=prompt('Project name','My first world');if(name===null)return;const next=project();next.name=name.trim()||'Untitled project';loadProject(next);note('Empty project created. Paint terrain, then place a player in Entities.')};
$('#sampleProject').onclick=()=>{if(!p.sample&&!confirm('Open the sample? Save your current project first if needed.'))return;loadProject(project(true));note('Opened the original Moonfern sample.')};
async function openProject(){try{const file=await chooseProjectFile($('#fileInput'));if(!file)return;if(file.text.length>10_000_000)throw Error('Project is too large. Maximum file size is 10 MB.');const next=validateExtended(JSON.parse(file.text));if(!p.sample&&!confirm('Replace the current project with this file?'))return;loadProject(next);note('Opened '+file.name)}catch(err){note('Could not open project: '+err.message,true)}}
$('#openProject').onclick=openProject;
$('#fileInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10_000_000)throw Error('Project is too large. Maximum file size is 10 MB.');const next=validateExtended(JSON.parse(await file.text()));if(!p.sample&&!confirm('Replace the current project with this file?'))return;loadProject(next);note('Opened '+file.name)}catch(err){note('Could not open project: '+err.message,true)}e.target.value=''};
const tourSteps=[
 {selector:'#projectBtn',title:'Project menu',description:'Open this menu to see the current project, resume saved work, create a new project, or open an existing .pixel.json file.'},
 {selector:'#save',title:'Save your project',description:'Save downloads an editable .pixel.json file. Your work also autosaves locally in the browser while you edit.'},
 {selector:'#play',title:'Playtest',description:'Press Playtest, or Enter, to try the current scene. The editor scene stays unchanged while you play.'},
 {selector:'#export',title:'Export a playable game',description:'Export creates a standalone HTML game you can share or open offline. It includes the current scene, artwork, and rules.'},
 {selector:'#themeToggle',title:'Pixel Playground skin',description:'Switch between the classic Pixel Forge look and the brighter kid-friendly Pixel Playground skin.'},
 {selector:'.left-panel',title:'Project panel',description:'Manage scenes and layers here. Select a scene, add a scene, duplicate it, or lock layers before painting.'},
 {selector:'#world',title:'World canvas',description:'This is your level. Paint tiles, place entities, move objects, draw shapes, and use the tool rail on the left.'},
 {selector:'[data-tab="tiles"]',title:'Tiles library',description:'Choose terrain, hazards, decorations, slopes, and other tiles. Then paint them onto the canvas.'},
 {selector:'[data-tab="entities"]',title:'Entities library',description:'Choose a player, enemy, pickup, door, NPC, platform, boss, or other object, then click the canvas to place it.'},
 {selector:'.inspector',title:'Inspector',description:'Select an object or tile to edit its name, position, behavior, artwork, collision, scene settings, and more.'},
 {selector:'[data-tab="audio"]',title:'Audio library',description:'Import sound effects and music, preview them, and keep them inside the local project file.'},
 {selector:'[data-tab="logic"]',title:'Logic rules',description:'Connect events such as switches, pickups, timers, and defeats to actions without writing code.'},
 {selector:'#collapse',title:'Panel controls',description:'Collapse or resize panels when you want more room for the canvas. Use the reset button to restore the layout.'}
];
let tourStep=0,tourTarget=null;
function clearTourTarget(){tourTarget?.classList.remove('tour-highlight');tourTarget=null;}
function renderTour(){const step=tourSteps[tourStep],target=document.querySelector(step.selector);clearTourTarget();$('#tourProgress').textContent=`${tourStep+1} / ${tourSteps.length}`;$('#tourTitle').textContent=step.title;$('#tourDescription').textContent=step.description;$('#tourBack').disabled=tourStep===0;$('#tourNext').textContent=tourStep===tourSteps.length-1?'Done ✓':'Next →';if(target){tourTarget=target;target.classList.add('tour-highlight');target.scrollIntoView?.({block:'center',inline:'nearest',behavior:'smooth'});}}
function closeTour(){clearTourTarget();if($('#tourDialog').open)$('#tourDialog').close();}
function startTour(){if(runtime)stop();if($('#welcome').open)$('#welcome').close();tourStep=0;$('#tourDialog').showModal();renderTour();}
$('#startTour').onclick=startTour;$('#tourBack').onclick=()=>{if(tourStep>0){tourStep--;renderTour()}};$('#tourNext').onclick=()=>{if(tourStep===tourSteps.length-1){closeTour();note('Tour complete. You can reopen it from the welcome screen.');}else{tourStep++;renderTour()}};$('#tourSkip').onclick=()=>{closeTour();note('Tour skipped. You can reopen it from the welcome screen.')};$('#tourDialog').addEventListener('close',clearTourTarget);
$('#projectBtn').onclick=welcome;$('#home').onclick=e=>{e.preventDefault();welcome()};$('#save').onclick=save;$('#play').onclick=play;$('#stop').onclick=stop;$('#undo').onclick=undo;$('#redo').onclick=redo;$('#themeToggle').onclick=()=>applySkin(document.documentElement.dataset.skin==='playground'?'classic':'playground');$('#help').onclick=()=>$('#helpDialog').showModal();$('#tutorial').onclick=startTour;
$('#newScene').onclick=()=>{if(runtime)stop();const name=prompt('New scene name','Untitled scene');if(name===null)return;checkpoint();p.scenes.push(initializeScene(makeScene(name.trim()||'Untitled scene')));p.activeScene=p.scenes.length-1;selected=null;changed();refresh();fit()};$('#duplicateScene').onclick=()=>{if(runtime)stop();checkpoint();const s=clone(scene());s.id=crypto.randomUUID();s.name+=' copy';s.entities.forEach(e=>e.id=crypto.randomUUID());p.scenes.push(s);p.activeScene=p.scenes.length-1;changed();refresh();fit()};
$('#addLayer').onclick=()=>{if(runtime)return;const name=prompt('New layer name','Decoration');if(!name?.trim())return;checkpoint();const l={id:crypto.randomUUID(),name:name.trim(),visible:true,locked:false,tiles:{}};scene().layers.push(l);layerId=l.id;changed();renderLayers();renderInspector()};
function duplicateEntity(){if(runtime)return;if(scene().layers.find(l=>l.id==='entities')?.locked){note('Unlock the Entities layer first.',true);return;}const e=scene().entities.find(e=>e.id===selected);if(!e)return;if(e.type==='player'){note('Each scene has one player spawn. Move it with Select.');return;}checkpoint();const n=clone(e);n.id=crypto.randomUUID();n.x=Math.min(scene().width*16-n.w,n.x+16);scene().entities.push(n);selected=n.id;changed();renderInspector()}
function deleteEntity(){if(runtime||!selected)return;if(scene().layers.find(l=>l.id==='entities')?.locked){note('Unlock the Entities layer first.',true);return;}checkpoint();scene().entities=scene().entities.filter(e=>e.id!==selected);selected=null;changed();renderInspector()}
$('#grid').onclick=()=>{grid=!grid;$('#grid').classList.toggle('active',grid)};$('#collision').onclick=()=>{showCollision=!showCollision;$('#collision').classList.toggle('active',showCollision)};$('#camera').onclick=()=>{showCamera=!showCamera;$('#camera').classList.toggle('active',showCamera)};$('#crt').onclick=()=>{crt=!crt;$('#crt').classList.toggle('active',crt)};$('#zoomIn').onclick=()=>zoomAt(zoom*1.25);$('#zoomOut').onclick=()=>zoomAt(zoom/1.25);$('#fit').onclick=fit;
$$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#assetSearch').oninput=renderAssets;$('#biome').onchange=()=>{if(runtime){$('#biome').value=scene().biome;return;}checkpoint();scene().biome=$('#biome').value;changed();renderAssets();renderInspector();renderPalette()};
mini.onclick=e=>{const r=mini.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*scene().width*16,y=(e.clientY-r.top)/r.width*scene().width*16;pan.x=canvas.width/2-x*zoom;pan.y=canvas.height/2-y*zoom;renderMini()};
window.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||document.querySelector('dialog[open]'))return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(workbench?.keyDown(e,k))return;if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter'].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if((e.metaKey||e.ctrlKey)&&k==='s'){e.preventDefault();save();return;}if(runtime){if(k==='Enter')stop();if(k==='Escape')runtime.paused=!runtime.paused;if(k==='r')void restartPlaytest();return;}if(e.metaKey||e.ctrlKey){if(k==='z'){e.preventDefault();e.shiftKey?redo():undo()}if(k==='d'){e.preventDefault();duplicateEntity()}return;}if(k==='Enter'){play();return;}if(k==='Delete'||k==='Backspace'){e.preventDefault();deleteEntity();return;}if(k==='g')$('#grid').click();else{const t=tools.find(t=>t[2].toLowerCase()===k);if(t)setTool(t[0]);}});
window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>{keys.clear();if(runtime)runtime.paused=true});
function exportSprite(){const c=document.createElement('canvas'),n=p.sprite.size;c.width=n*p.sprite.frames.length;c.height=n;const x=c.getContext('2d');p.sprite.frames.forEach((f,i)=>f.forEach((col,j)=>{if(col){x.fillStyle=col;x.fillRect(i*n+j%n,Math.floor(j/n),1,1)}}));c.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pixel-forge-sprite-sheet.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)});note('Sprite sheet exported as transparent PNG.')}
$('#spriteInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const img=await createImageBitmap(file),n=p.sprite.size;if(img.width%n||img.height%n||img.width*img.height>1_048_576)throw Error(`Use a sheet with dimensions divisible by ${n}, up to 1 megapixel.`);const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const x=c.getContext('2d');x.drawImage(img,0,0);const frames=[];for(let y=0;y<img.height;y+=n)for(let xx=0;xx<img.width;xx+=n){const data=x.getImageData(xx,y,n,n).data,f=[];for(let i=0;i<data.length;i+=4)f.push(data[i+3]===0?null:`rgba(${data[i]},${data[i+1]},${data[i+2]},${data[i+3]/255})`);frames.push(f)}checkpoint();p.sprite.frames=frames;spriteFrame=0;changed();setMode('sprite');renderAssets();note(`Imported ${frames.length} frames.`);img.close()}catch(err){note('Import failed: '+err.message,true)}e.target.value=''};
$('#audioInput').onchange=async e=>{const kind=e.target.dataset.kind==='music'?'music':'effects';const files=[...e.target.files];e.target.value='';if(!files.length)return;try{const total=p.audio.effects.concat(p.audio.music).reduce((sum,a)=>sum+a.bytes,0);let added=0,imports=[];for(const file of files){if(!file.type.startsWith('audio/'))throw Error(`${file.name} is not an audio file.`);if(file.size>MAX_AUDIO_FILE)throw Error(`${file.name} is larger than 4 MB.`);if(total+added+file.size>MAX_AUDIO_TOTAL)throw Error('The project audio library is limited to 8 MB.');const data=await readDataURL(file);imports.push({id:crypto.randomUUID(),name:file.name.replace(/\.[^.]+$/,''),mime:file.type,bytes:file.size,data,loop:kind==='music'});added+=file.size;}checkpoint();p.audio[kind].push(...imports);changed();renderAssets();note(`Imported ${files.length} audio file${files.length===1?'':'s'}.`)}catch(err){note('Audio import failed: '+err.message,true)}};
$('#export').onclick=async()=>{try{new Runtime(scene(),p);const html=await buildGameHTML(p,scene().id);if(await download(html,p.name.replace(/[^a-z0-9]/gi,'-')+'-game.html','text/html')){note('Game exported with all scenes, assets and event rules.');workbench?.completeTutorial('export')}}catch(e){note('Export failed: '+e.message,true)}};
try{const saved=localStorage.getItem('pixel-forge-autosave');if(saved)p=validateExtended(JSON.parse(saved));}catch{note('Could not restore the last autosave. You can open a saved project file.',true)}
workbench=mountWorkbench({
 get project(){return p}, get scene(){return scene()},get layer(){return layer()},get layerId(){return layerId},set layerId(v){layerId=v},
 get selected(){return selected},set selected(v){selected=v},get mode(){return mode},get tool(){return tool},get tab(){return tab},
 get spriteFrame(){return spriteFrame},set spriteFrame(v){spriteFrame=v},get color(){return color},set color(v){color=v},
 get runtime(){return runtime},get zoom(){return zoom},get pan(){return pan},get tileId(){return tileId},set tileId(v){tileId=v},
 canvas,ctx,keys,checkpoint,changed,refresh,renderInspector,renderAssets,renderLayers,renderPalette,renderScenes,renderMini,
 setMode,setTool,setTab,fit,note,loadProject,download,save,play,stop,exportSprite,projectStore,undo,redo,thumb,
 get onion(){return onion},set onion(v){onion=v},get animate(){return animate},set animate(v){animate=v;animationStart=performance.now()/1000},importAudio,updateAudio,removeAudio,
 get grid(){return grid},set grid(v){grid=v},writeCell,point,cell
});
 initLayout();resize();refresh();fit();requestAnimationFrame(frame);setTimeout(()=>{document.body.classList.add('app-ready');welcome();},3000);
