import {clone,project,entity,tiles,palettes,gameTypes,biomeNames,eventTypes,actionTypes,createRule,initializeScene} from './model.js';
import {templateProject} from './templates.js';
import {drawEntity,drawScene} from './render.js';

export const node=(tag,className,text)=>{const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n;};
export const button=(text,fn,className='')=>{const b=node('button',className,text);b.type='button';b.onclick=fn;return b;};
export function field(parent,label,value,change,options={}){
 const wrap=node('label','field'),name=node('span','',label),input=document.createElement(options.choices?'select':options.multiline?'textarea':'input');
 if(options.choices)for(const entry of options.choices){const [key,text]=Array.isArray(entry)?entry:[entry,entry];const opt=node('option','',text);opt.value=key;input.append(opt);}
 else if(!options.multiline)input.type=options.type||(typeof value==='boolean'?'checkbox':typeof value==='number'?'number':'text');
 if(input.type==='checkbox')input.checked=value;else input.value=value??'';
 for(const key of ['min','max','step','placeholder','maxLength'])if(options[key]!==undefined)input[key]=options[key];
 input.onchange=()=>{if(input.validity&&!input.validity.valid){input.reportValidity();return;}change(input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value);};
 wrap.append(name,input);parent.append(wrap);return input;
}
export function dialog(title){const d=node('dialog','workbench-dialog'),close=button('×',()=>d.close(),'dialog-close');close.setAttribute('aria-label','Close');d.append(close,node('h2','',title));document.body.append(d);d.addEventListener('close',()=>d.remove());return d;}

export function clearSceneReferences(project,sceneId){for(const scene of project.scenes){for(const e of scene.entities)if(e.targetScene===sceneId)e.targetScene='';for(const rule of scene.events||[])if(rule.action==='scene'&&rule.targetId===sceneId)rule.targetId='';}}
export function removeEntityRules(project,entityId){for(const scene of project.scenes)scene.events=(scene.events||[]).filter(rule=>rule.sourceId!==entityId&&!(rule.targetId===entityId&&rule.action!=='scene'));}
export function createPanels(api){
 let editingAssetId=null,lastProject=api.project.id;
 const originalPalettes=clone(palettes),tileTransform={flipX:false,flipY:false,rotation:0};
 const mutate=fn=>{if(api.runtime){api.note('Stop playtest to edit your project.');return;}api.checkpoint();fn();api.changed();api.refresh();};
 const entityOptions=()=>[['*','Any object'],...api.scene.entities.map(e=>[e.id,`${e.name} (${e.type})`])];
 const section=(parent,title)=>{const s=node('section','inspect-section');s.append(node('h3','',title));parent.append(s);return s;};
 const editField=(parent,label,obj,key,options={})=>field(parent,label,obj[key],v=>mutate(()=>obj[key]=v),options);
 const assignedEntity=()=>api.scene.entities.find(e=>e.id===api.selected);
 function spriteThumbnail(asset){const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d');x.imageSmoothingEnabled=false;x.fillStyle='#181924';x.fillRect(0,0,64,64);x.scale(64/asset.size,64/asset.size);asset.frames[0]?.forEach((col,i)=>{if(col){x.fillStyle=col;x.fillRect(i%asset.size,Math.floor(i/asset.size),1,1);}});return c;}
 function saveSprite(){const a=clone(api.project.sprite);if(!a.frames.some(f=>f.some(Boolean))){api.note('Paint or import a sprite before adding it to the library.');return;}const name=prompt('Sprite name',a.name||'My sprite');if(!name?.trim())return;const used=api.scene.entities.map(e=>/^Sprite (\d+)$/.exec(e.name||'')?.[1]).filter(Boolean).map(Number);const nextName=`Sprite ${used.length?Math.max(...used)+1:1}`;mutate(()=>{a.id=crypto.randomUUID();a.name=name.trim();a.folder||='Sprites';api.project.assets.push(a);editingAssetId=a.id;api.project.sprite=clone(a);const placed=entity('custom',Math.max(0,Math.floor(api.scene.width/2)*16-a.size/2),Math.max(0,Math.floor(api.scene.height/2)*16-a.size/2));placed.name=nextName;placed.spriteId=a.id;placed.w=Math.max(12,Math.min(64,a.size));placed.h=Math.max(16,Math.min(64,a.size));api.scene.entities.push(placed);api.selected=placed.id;});api.note(`Sprite saved and added to Entities as ${nextName}.`);}
 function editSprite(asset){editingAssetId=asset.id;api.project.sprite=clone(asset);api.spriteFrame=0;api.setMode('sprite');api.renderInspector();api.setTab('animation');}
 function removeAsset(asset){if(!confirm(`Delete “${asset.name}”? Entities using it return to their built-in artwork. Undo restores it.`))return;mutate(()=>{api.project.assets=api.project.assets.filter(a=>a.id!==asset.id);for(const s of api.project.scenes)for(const e of s.entities)if(e.spriteId===asset.id)e.spriteId='';if(editingAssetId===asset.id)editingAssetId=null;});}
 function renderSprites(host){
  host.className='sprite-library';const bar=node('div','panel-actions');bar.append(button('＋ New sprite',()=>{mutate(()=>{editingAssetId=null;api.project.sprite={id:'custom',name:'Untitled sprite',size:16,frames:[Array(256).fill(null)],timing:160,mode:'loop',folder:'Sprites',tags:[]};api.spriteFrame=0;});api.setMode('sprite');}),button('Save drawing to library',saveSprite),button('↑ Import PNG',()=>document.querySelector('#spriteInput').click()),button('↓ PNG sheet',api.exportSprite));host.append(bar);
  const assets=api.project.assets.filter(a=>(a.name+' '+a.folder+' '+(a.tags||[]).join(' ')).toLowerCase().includes(document.querySelector('#assetSearch').value.toLowerCase()));
  if(!assets.length)host.append(node('p','empty-copy','Draw a sprite in Sprite mode, then save it to your library. Assign it to a player, enemy, prop, or pickup.'));
  const grid=node('div','sprite-library-grid');for(const a of assets){const card=node('article','sprite-library-card');const preview=button('',()=>editSprite(a),'sprite-preview');preview.append(spriteThumbnail(a));card.append(preview,node('strong','',a.name),node('small','',`${a.size}×${a.size} · ${a.frames.length} frames · ${a.folder}`));const actions=node('div','panel-actions');actions.append(button('Edit',()=>editSprite(a)),button('Duplicate',()=>mutate(()=>{const copy=clone(a);copy.id=crypto.randomUUID();copy.name+=' copy';api.project.assets.push(copy);})),button('Delete',()=>removeAsset(a)));card.append(actions);grid.append(card);}host.append(grid);return true;
 }
 function renderInspector(){
  const host=document.querySelector('#inspection');host.replaceChildren();const e=assignedEntity(),s=api.scene;
  if(api.mode==='sprite'){
   const a=api.project.sprite,title=node('div','inspect-title');title.append(spriteThumbnail(a),node('strong','',a.name));host.append(title);
   let sec=section(host,'SPRITE ASSET');editField(sec,'Name',a,'name',{maxLength:80});editField(sec,'Folder',a,'folder',{choices:api.project.folders});field(sec,'Tags',(a.tags||[]).join(', '),v=>mutate(()=>a.tags=v.split(',').map(x=>x.trim()).filter(Boolean)));
   field(sec,'Canvas size',a.size,v=>{if(!confirm('Resize every frame? Pixels outside the new bounds will be cropped. Undo restores them.'))return;mutate(()=>{const old=a.size,n=Number(v);a.frames=a.frames.map(f=>Array.from({length:n*n},(_,i)=>i%n<old&&Math.floor(i/n)<old?f[Math.floor(i/n)*old+i%n]:null));a.size=n;});},{choices:[8,16,24,32,64].map(n=>[n,`${n} × ${n}`])});
   sec=section(host,'ANIMATION');editField(sec,'Frame time (ms)',a,'timing',{min:30,max:2000});editField(sec,'Playback',a,'mode',{choices:['loop','ping-pong','one-shot']});field(sec,'Onion skin',api.onion,v=>{api.onion=v;});
   const transform=(vertical)=>mutate(()=>{const n=a.size,f=a.frames[api.spriteFrame];a.frames[api.spriteFrame]=Array.from({length:n*n},(_,i)=>f[vertical?(n-1-Math.floor(i/n))*n+i%n:Math.floor(i/n)*n+n-1-i%n]);});sec.append(button('↔ Flip',()=>transform(false)),button('↕ Flip',()=>transform(true)),button('Save to library',saveSprite));
   sec=section(host,'COLOR');field(sec,'Selected swatch',palettes[s.biome][api.color],v=>mutate(()=>{api.project.paletteOverrides[s.biome]??=[...palettes[s.biome]];api.project.paletteOverrides[s.biome][api.color]=v;}),{type:'color'});field(sec,'Palette locked',a.paletteLocked??true,v=>mutate(()=>a.paletteLocked=v));
   host.append(node('p','inspector-note','Paint with the palette below. The drawing can be assigned directly as “Current drawing”, or saved as a reusable sprite asset.'));return true;
  }
  if(e){
   const title=node('div','inspect-title'),c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d');x.imageSmoothingEnabled=false;x.scale(2,2);drawEntity(x,{...e,x:4,y:2},palettes[s.biome],0,{assets:api.project.assets,customSprite:api.project.sprite});title.append(c,node('strong','',e.name));host.append(title);
   const locked=s.layers.find(l=>l.id==='entities')?.locked; if(locked){host.append(node('p','inspector-note','Entities layer is locked. Unlock it to change this object.'));return true;}
   let sec=section(host,'TRANSFORM');editField(sec,'Name',e,'name',{maxLength:80});for(const [label,key,max] of [['X','x',s.width*16-e.w],['Y','y',s.height*16-e.h],['Width','w',256],['Height','h',256]])editField(sec,label,e,key,{min:key==='w'||key==='h'?1:0,max});editField(sec,'Visible',e,'visible');
   if(e.type==='prop'){sec=section(host,'GARDEN DEPTH');editField(sec,'Elevation / arch',e,'elevation',{min:0,max:64});editField(sec,'Depth offset',e,'depthOffset',{min:-128,max:128});editField(sec,'Solid footprint',e,'solid');host.append(node('p','inspector-note','Width and height define the ground footprint. Elevation shapes the artwork. Bridges provide an upper walking surface.'));}
   sec=section(host,'ARTWORK');editField(sec,'Sprite',e,'spriteId',{choices:[['','Built-in artwork'],['custom','Current drawing'],...api.project.assets.map(a=>[a.id,a.name])]});editField(sec,'Flip X',e,'flipX');editField(sec,'Flip Y',e,'flipY');editField(sec,'Scale',e,'scale',{min:.25,max:8,step:.25});editField(sec,'Rotation',e,'rotation',{choices:[0,90,180,270]});
   if(['player','enemy','boss','platform','emitter','hazard','breakable'].includes(e.type)){
    sec=section(host,'BEHAVIOR');editField(sec,'Movement',e,'behavior',{choices:['stationary','patrol','flying','chasing','ambush','projectile','rider','shielded','destructible','timed','moving','boss']});for(const [label,key,min,max] of [['Speed','speed',0,500],['Health','health',1,99],['Damage','damage',0,20],['Patrol distance','patrol',0,1024],['Period (sec)','period',.1,60]])editField(sec,label,e,key,{min,max,step:key==='period'?.1:1});
    editField(sec,'Direction',e,'direction',{choices:[[1,'Right'],[-1,'Left'],['up','Up'],['down','Down']]});
    if(e.type==='player'){editField(sec,'Jump velocity',e,'jump',{min:0,max:900});editField(sec,'Gravity',e,'gravity',{min:100,max:2400});editField(sec,'Acceleration',e,'acceleration',{min:100,max:4000});}
    sec.append(button('Edit movement path',()=>{api.setTool('path');api.note('Click the canvas to add path points. Select the object again to inspect.');}),button('Clear path',()=>mutate(()=>e.path=[])));
   }
   if(['door','transition'].includes(e.type)){sec=section(host,'DESTINATION');editField(sec,'Next scene',e,'targetScene',{choices:[['','Complete this stage'],...api.project.scenes.filter(x=>x.id!==s.id).map(x=>[x.id,x.name])]});editField(sec,'Locked',e,'locked');editField(sec,'Required key ID',e,'keyId');}
   if(e.type==='key'){sec=section(host,'KEY');editField(sec,'Key ID',e,'keyId');}
   if(['npc','trigger','savepoint'].includes(e.type)){sec=section(host,'INTERACTION');editField(sec,'Dialogue text',e,'text',{multiline:true,maxLength:1000});}
   sec=section(host,'OBJECT ID');const id=node('code','entity-id',e.id);sec.append(id,button('Add event for this object',()=>{mutate(()=>{const r=createRule();r.sourceId=e.id;r.event=e.type==='switch'?'switch':'enter';s.events.push(r);});api.setTab('logic');}));
   sec.append(button('Duplicate',()=>{if(e.type==='player'){api.note('A scene has one player spawn.');return;}mutate(()=>{const copy=clone(e);copy.id=crypto.randomUUID();copy.x=Math.min(s.width*16-copy.w,copy.x+16);s.entities.push(copy);api.selected=copy.id;});}),button('Delete',()=>mutate(()=>{removeEntityRules(api.project,e.id);s.entities=s.entities.filter(x=>x.id!==e.id);api.selected=null;})));return true;
  }
  const t=tiles.find(t=>t.id===api.tileId);const title=node('div','inspect-title');title.append(api.thumb('tile',t.id),node('strong','',t.name));host.append(title);
  let sec=section(host,'BRUSH');sec.append(node('p','inspector-note',`${t.category} · ${t.solid?'Solid':'Pass-through'} · 16 × 16 pixels`));field(sec,'Flip X',tileTransform.flipX,v=>tileTransform.flipX=v);field(sec,'Flip Y',tileTransform.flipY,v=>tileTransform.flipY=v);field(sec,'Rotation',tileTransform.rotation,v=>tileTransform.rotation=Number(v),{choices:[0,90,180,270]});editField(sec,'Connect terrain',s,'autotile');
  sec=section(host,'SCENE');editField(sec,'Name',s,'name',{maxLength:80});editField(sec,'Game format',s,'gameType',{choices:Object.entries(gameTypes)});editField(sec,'Environment',s,'biome',{choices:Object.entries(biomeNames)});for(const [label,key,min,max] of [['Camera width','w',160,640],['Camera height','h',120,384]])editField(sec,label,s.camera,key,{min,max});
  sec.append(button('Configure HUD',()=>api.setTab('hud')),button('Project settings',showSettings));
  sec=section(host,'LAYER');const layer=api.layer;editField(sec,'Name',layer,'name');const actions=node('div','panel-actions');actions.append(button('↑',()=>reorderLayer(1)),button('↓',()=>reorderLayer(-1)),button('Duplicate',()=>mutate(()=>{const copy=clone(layer);copy.id=crypto.randomUUID();copy.name+=' copy';s.layers.splice(s.layers.indexOf(layer)+1,0,copy);api.layerId=copy.id;})));sec.append(actions);return true;
 }
 function reorderLayer(dir){mutate(()=>{const ls=api.scene.layers,i=ls.findIndex(l=>l.id===api.layerId),j=i+dir;if(j>=0&&j<ls.length)[ls[i],ls[j]]=[ls[j],ls[i]];});}
 function renderLogic(host){
  host.className='logic-editor';const intro=node('div','panel-actions');intro.append(node('strong','','When this happens → do this'),button('＋ Add interaction',()=>mutate(()=>api.scene.events.push(createRule()))));host.append(intro);
  if(!api.scene.events.length)host.append(node('p','empty-copy','Connect a switch to a door, a collected item to dialogue, or a timer to an enemy spawn. No code needed.'));
  for(const rule of api.scene.events){const row=node('article','logic-rule');const top=node('div','panel-actions');top.append(node('strong','',rule.name));field(top,'Enabled',rule.enabled,v=>mutate(()=>rule.enabled=v));field(top,'Once',rule.once,v=>mutate(()=>rule.once=v));top.append(button('Remove',()=>mutate(()=>api.scene.events=api.scene.events.filter(x=>x.id!==rule.id))));row.append(top);
   const flow=node('div','logic-flow'),when=node('div','logic-node'),then=node('div','logic-node');when.append(node('span','logic-label','WHEN'));editField(when,'Event',rule,'event',{choices:Object.entries(eventTypes)});editField(when,'Source',rule,'sourceId',{choices:entityOptions()});if(rule.event==='timer')field(when,'Every seconds',rule.period??1,v=>mutate(()=>rule.period=v),{type:'number',min:.1,max:3600,step:.1});
   then.append(node('span','logic-label','THEN'));editField(then,'Action',rule,'action',{choices:Object.entries(actionTypes)});const targets=rule.action==='scene'?api.project.scenes.map(s=>[s.id,s.name]):entityOptions();editField(then,'Target',rule,'targetId',{choices:[['','Choose target'],...targets]});editField(then,'Delay seconds',rule,'delay',{min:0,max:3600,step:.1});
   if(rule.action==='palette')editField(then,'Palette',rule,'value',{choices:[['','Choose palette'],...Object.entries(biomeNames)]});else if(['message','dialogue','item','sound','shake','animation','boss'].includes(rule.action)){if(rule.action==='sound'){const audio=[...(api.project.audio.effects||[]),...(api.project.audio.music||[])];editField(then,'Audio',rule,'value',{choices:[['','Choose audio'],...audio.map(a=>[a.id,`${a.name}${a.loop?' · music':''}`])]});}else editField(then,'Value',rule,'value',{maxLength:1000});}
   flow.append(when,node('span','logic-arrow','→'),then);row.append(flow);host.append(row);}
 }
 function renderHUD(host){host.className='hud-editor';const form=node('div','hud-options');for(const key of ['health','score','timer','lives','keys','boss'])editField(form,key[0].toUpperCase()+key.slice(1),api.scene.hud,key);editField(form,'Objective',api.scene.hud,'objective',{maxLength:120});host.append(form);const preview=node('div','hud-preview');preview.append(node('span','','HUD PREVIEW'));const enabled=Object.keys(api.scene.hud).filter(k=>api.scene.hud[k]&&k!=='objective');preview.append(node('strong','',enabled.map(k=>({health:'♥ ♥ ♥',score:'00000',timer:'0:00',lives:'L 3',keys:'K 0',boss:'BOSS ▰▰▰▰'})[k]).join('    ')),node('p','',api.scene.hud.objective||'Your scene objective appears here.'));host.append(preview);}
 function formatBytes(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${Math.round(bytes/1024)} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`;}
 function renderAudio(host){host.className='audio-library';const actions=node('div','panel-actions');actions.append(button('↑ Import sound effects',()=>api.importAudio('effects')),button('↑ Import music',()=>api.importAudio('music')));host.append(actions,node('p','audio-help','Audio is stored inside the project. Effects are one-shot; music can loop. Use the Logic tab to trigger imported audio from gameplay events.'));for(const kind of ['effects','music']){const list=api.project.audio[kind],section=node('section','audio-section'),heading=node('div','audio-section-heading');heading.append(node('strong','',kind==='effects'?'SOUND EFFECTS':'MUSIC'),node('span','',`${list.length} file${list.length===1?'':'s'}`));section.append(heading);if(!list.length)section.append(node('p','empty-copy',kind==='effects'?'Import clicks, jumps, hits, and UI sounds.':'Import a music loop or title theme.'));for(const asset of list){const card=node('article','audio-card'),meta=node('div','audio-meta');meta.append(node('strong','',asset.name),node('small','',`${formatBytes(asset.bytes)} · ${asset.mime.replace('audio/','').toUpperCase()}`));const audio=document.createElement('audio');audio.src=asset.data;audio.preload='metadata';audio.controls=true;audio.loop=asset.loop;const controls=node('div','panel-actions');const loop=field(controls,'Loop',asset.loop,v=>api.updateAudio(asset.id,kind,{loop:v}));loop.className='audio-loop';controls.append(button('Delete',()=>api.removeAudio(asset.id,kind)));card.append(meta,audio,controls);section.append(card);}host.append(section);}return true;}
 function renderFiles(host){host.className='project-files';const p=api.project;const actions=node('div','panel-actions');actions.append(button('Download project',api.save),button('Save as…',()=>{const name=prompt('Save a new project copy',p.name+' copy');if(!name?.trim())return;const copy=clone(p);copy.id=crypto.randomUUID();copy.name=name.trim();api.loadProject(copy);api.save();}),button('New folder',()=>{const name=prompt('Asset folder name');if(name?.trim()&&!p.folders.includes(name.trim()))mutate(()=>p.folders.push(name.trim()));}));host.append(actions);
  const tree=node('pre','file-tree');tree.textContent=`${p.name}/\n├─ project.json\n├─ scenes/\n${p.scenes.map(s=>`│  ├─ ${s.name}.json (${s.entities.length} objects)`).join('\n')}\n├─ assets/\n${p.assets.map(a=>`│  ├─ ${a.folder}/${a.name}.json`).join('\n')}\n├─ palettes/ (${Object.keys(p.paletteOverrides).length} custom)\n└─ settings.json\n\nThe downloaded .pixel.json contains this complete project structure.`;host.append(tree);
  const versions=api.projectStore.versions(p.id);const group=node('div','version-list');group.append(node('strong','','Version history'));for(const v of versions){const row=node('div','project-row');row.append(node('span','',`${new Date(v.at).toLocaleString()} · ${v.name}`),button('Restore',()=>{const recovered=api.projectStore.restoreVersion(p.id,v.id);if(recovered)api.loadProject(recovered);}));group.append(row);}host.append(group);
 }
 function renderCollision(host){host.className='collision-editor';const entries=Object.entries(api.scene.collision);host.append(node('p','empty-copy',`${entries.length} collision overrides. The collision brush toggles a tile between solid and pass-through.`),button('Edit collisions',()=>api.setTool('collision')),button('Reset overrides',()=>{if(confirm('Reset all custom collision overrides? Undo restores them.'))mutate(()=>api.scene.collision={});}));for(const[key,solid]of entries.slice(0,200)){const row=node('div','project-row');row.append(node('span','',`${key} · ${solid?'Solid':'Pass-through'}`),button('Reset cell',()=>mutate(()=>delete api.scene.collision[key])));host.append(row);}}
 function showSettings(){
  const d=dialog('Project settings'),p=api.project;field(d,'Project name',p.name,v=>mutate(()=>p.name=v),{maxLength:100});field(d,'High contrast',p.settings.highContrast,v=>mutate(()=>p.settings.highContrast=v));field(d,'Reduced motion',p.settings.reducedMotion,v=>mutate(()=>p.settings.reducedMotion=v));field(d,'UI scale',p.settings.uiScale,v=>mutate(()=>p.settings.uiScale=Number(v)),{choices:[[90,'Compact'],[100,'Default'],[115,'Large']]});field(d,'Sound',p.settings.sound,v=>mutate(()=>p.settings.sound=v));field(d,'Volume',p.settings.volume,v=>mutate(()=>p.settings.volume=v),{min:0,max:1,step:.05});
  d.append(node('h3','','Keyboard shortcuts'));for(const [id,defaultKey]of [['select','v'],['pencil','b'],['eraser','e'],['fill','f'],['rectangle','r'],['line','l'],['eyedropper','i'],['entity','n'],['collision','c'],['camera','k'],['pan','h'],['path','p'],['stamp','t'],['measure','m']])field(d,id,p.settings.shortcuts[id]||defaultKey,v=>{v=v.toLowerCase();if(v.length!==1||Object.entries(p.settings.shortcuts).some(([k,x])=>k!==id&&x===v)){api.note('Choose a unique single letter.');return;}mutate(()=>p.settings.shortcuts[id]=v);},{maxLength:1});d.showModal();
 }
 function showProjects(){const d=dialog('Your local projects');let list=[];try{list=api.projectStore.list();}catch(e){api.note(e.message,true);}if(!list.length)d.append(node('p','empty-copy','Your saved projects appear here. No account is required.'));for(const p of list){const row=node('div','project-row');row.append(node('span','',`${p.name} · ${p.sceneCount} scene${p.sceneCount===1?'':'s'}`),button('Open',()=>{api.loadProject(api.projectStore.load(p.id));d.close();}),button('Trash',()=>{if(p.id===api.project.id){api.note('Open another project before moving this one to trash.');return;}api.projectStore.remove(p.id);d.close();showProjects();}));d.append(row);}for(const p of api.projectStore.listTrash()){const row=node('div','project-row');row.append(node('span','',`Trash · ${p.name}`),button('Restore',()=>{api.projectStore.restoreTrash(p.id);d.close();showProjects();}));d.append(row);}d.showModal();}
 function init(){
  const settings=button('⚙',showSettings);settings.title='Project settings';document.querySelector('.actions').insertBefore(settings,document.querySelector('#help'));
  const manage=button('▱ All saved projects',showProjects,'quiet');document.querySelector('.project-tree').append(manage);
  for(const[id,label]of [['files','▱ Files'],['hud','♥ HUD'],['collisions','▧ Solids']]){const b=button(label,()=>api.setTab(id));b.dataset.tab=id;document.querySelector('.asset-tabs').insertBefore(b,document.querySelector('#collapse'));}
  const biome=document.querySelector('#biome');biome.replaceChildren();for(const[k,v]of Object.entries(biomeNames)){const opt=node('option','',v);opt.value=k;biome.append(opt);}
  const welcome=document.querySelector('.welcome-actions');welcome.append(button('◇ Create a top-down adventure',()=>api.loadProject(templateProject('topdown'))),button('▣ Create a 2.5D water world',()=>api.loadProject(templateProject('2.5d'))),button('✦ Create an arcade stage',()=>api.loadProject(templateProject('arcade'))),button('▱ All saved projects',showProjects));
  const deleteScene=button('− Delete scene',()=>{if(api.project.scenes.length<=1){api.note('A project needs at least one scene.');return;}if(!confirm(`Delete “${api.scene.name}”? Undo restores the scene.`))return;mutate(()=>{const id=api.scene.id;api.project.scenes.splice(api.project.activeScene,1);api.project.activeScene=Math.max(0,api.project.activeScene-1);clearSceneReferences(api.project,id);api.selected=null;});},'quiet');document.querySelector('.project-tree').append(deleteScene);
 }
 init();
 return {tileTransform,showSettings,showProjects,renderInspector,
  syncSprite(){if(api.project.id!==lastProject){editingAssetId=null;lastProject=api.project.id;}if(editingAssetId){const index=api.project.assets.findIndex(x=>x.id===editingAssetId);if(index>=0)api.project.assets[index]={...clone(api.project.sprite),id:editingAssetId};}},
  restorePalette(){for(const [id,p]of Object.entries(originalPalettes))palettes[id]=[...(api.project.paletteOverrides[id]||p)];},
  refresh(){document.body.classList.toggle('high-contrast',api.project.settings.highContrast);document.body.classList.toggle('reduced-motion',api.project.settings.reducedMotion);document.documentElement.style.setProperty('--ui-scale',api.project.settings.uiScale/100);},
  renderAssets(tab){if(!['sprites','logic','hud','files','collisions','audio'].includes(tab))return false;const host=document.querySelector('#assets');host.replaceChildren();document.querySelector('.asset-filters').hidden=!['sprites','audio'].includes(tab);document.querySelector('#assetCount').textContent=tab==='audio'?`${api.project.audio.effects.length+api.project.audio.music.length} audio files`:api.project.assets.length+' assets';({sprites:renderSprites,logic:renderLogic,hud:renderHUD,files:renderFiles,collisions:renderCollision,audio:renderAudio})[tab](host);return true;}
 };
}
